unfrozen_parameters:
- ^lm_head.weight$
- ^model.embed_tokens.weight$
# input_layernorm layers
- model.layers.0.input_layernorm
- model.layers.1.input_layernorm
- model.layers.2.input_layernorm
- model.layers.3.input_layernorm
- model.layers.4.input_layernorm
- model.layers.5.input_layernorm
- model.layers.6.input_layernorm
- model.layers.7.input_layernorm
- model.layers.8.input_layernorm
- model.layers.9.input_layernorm
- model.layers.10.input_layernorm
- model.layers.11.input_layernorm
- model.layers.12.input_layernorm
- model.layers.13.input_layernorm
- model.layers.14.input_layernorm
- model.layers.15.input_layernorm
- model.layers.16.input_layernorm
- model.layers.17.input_layernorm
- model.layers.18.input_layernorm
- model.layers.19.input_layernorm
- model.layers.20.input_layernorm
- model.layers.21.input_layernorm
- model.layers.22.input_layernorm
- model.layers.23.input_layernorm
# lm_head layers
# mlp.down_proj layers
- model.layers.18.mlp.down_proj
- model.layers.17.mlp.down_proj
- model.layers.9.mlp.down_proj
- model.layers.8.mlp.down_proj
- model.layers.10.mlp.down_proj
- model.layers.6.mlp.down_proj
- model.layers.5.mlp.down_proj
- model.layers.7.mlp.down_proj
- model.layers.2.mlp.down_proj
- model.layers.11.mlp.down_proj
- model.layers.12.mlp.down_proj
- model.layers.16.mlp.down_proj
- model.layers.4.mlp.down_proj
- model.layers.3.mlp.down_proj
- model.layers.13.mlp.down_proj
- model.layers.15.mlp.down_proj
- model.layers.1.mlp.down_proj
- model.layers.14.mlp.down_proj
- model.layers.0.mlp.down_proj
- model.layers.19.mlp.down_proj
- model.layers.20.mlp.down_proj
- model.layers.21.mlp.down_proj
- model.layers.22.mlp.down_proj
- model.layers.23.mlp.down_proj
# mlp.gate_proj layers
- model.layers.17.mlp.gate_proj
- model.layers.12.mlp.gate_proj
- model.layers.18.mlp.gate_proj
- model.layers.16.mlp.gate_proj
- model.layers.7.mlp.gate_proj
- model.layers.10.mlp.gate_proj
- model.layers.14.mlp.gate_proj
- model.layers.13.mlp.gate_proj
- model.layers.15.mlp.gate_proj
- model.layers.6.mlp.gate_proj
- model.layers.11.mlp.gate_proj
- model.layers.8.mlp.gate_proj
- model.layers.1.mlp.gate_proj
- model.layers.4.mlp.gate_proj
- model.layers.2.mlp.gate_proj
- model.layers.3.mlp.gate_proj
- model.layers.9.mlp.gate_proj
- model.layers.5.mlp.gate_proj
- model.layers.0.mlp.gate_proj
- model.layers.19.mlp.gate_proj
- model.layers.20.mlp.gate_proj
- model.layers.21.mlp.gate_proj
- model.layers.22.mlp.gate_proj
- model.layers.23.mlp.gate_proj
# mlp.up_proj layers
- model.layers.18.mlp.up_proj
- model.layers.17.mlp.up_proj
- model.layers.16.mlp.up_proj
- model.layers.15.mlp.up_proj
- model.layers.12.mlp.up_proj
- model.layers.14.mlp.up_proj
- model.layers.13.mlp.up_proj
- model.layers.7.mlp.up_proj
- model.layers.10.mlp.up_proj
- model.layers.6.mlp.up_proj
- model.layers.11.mlp.up_proj
- model.layers.8.mlp.up_proj
- model.layers.1.mlp.up_proj
- model.layers.4.mlp.up_proj
- model.layers.3.mlp.up_proj
- model.layers.2.mlp.up_proj
- model.layers.9.mlp.up_proj
- model.layers.5.mlp.up_proj
- model.layers.0.mlp.up_proj
- model.layers.19.mlp.up_proj
- model.layers.20.mlp.up_proj
- model.layers.21.mlp.up_proj
- model.layers.22.mlp.up_proj
- model.layers.23.mlp.up_proj
# model.embed_tokens layers
# model.norm layers
# post_attention_layernorm layers
- model.layers.0.post_attention_layernorm
- model.layers.1.post_attention_layernorm
- model.layers.2.post_attention_layernorm
- model.layers.3.post_attention_layernorm
- model.layers.4.post_attention_layernorm
- model.layers.5.post_attention_layernorm
- model.layers.6.post_attention_layernorm
- model.layers.7.post_attention_layernorm
- model.layers.8.post_attention_layernorm
- model.layers.9.post_attention_layernorm
- model.layers.10.post_attention_layernorm
- model.layers.11.post_attention_layernorm
- model.layers.12.post_attention_layernorm
- model.layers.13.post_attention_layernorm
- model.layers.14.post_attention_layernorm
- model.layers.15.post_attention_layernorm
- model.layers.16.post_attention_layernorm
- model.layers.17.post_attention_layernorm
- model.layers.18.post_attention_layernorm
- model.layers.19.post_attention_layernorm
- model.layers.20.post_attention_layernorm
- model.layers.21.post_attention_layernorm
- model.layers.22.post_attention_layernorm
- model.layers.23.post_attention_layernorm
# self_attn.k_proj layers
- model.layers.2.self_attn.k_proj
- model.layers.18.self_attn.k_proj
- model.layers.17.self_attn.k_proj
- model.layers.15.self_attn.k_proj
- model.layers.16.self_attn.k_proj
- model.layers.14.self_attn.k_proj
- model.layers.7.self_attn.k_proj
- model.layers.10.self_attn.k_proj
- model.layers.13.self_attn.k_proj
- model.layers.6.self_attn.k_proj
- model.layers.11.self_attn.k_proj
- model.layers.12.self_attn.k_proj
- model.layers.4.self_attn.k_proj
- model.layers.9.self_attn.k_proj
- model.layers.8.self_attn.k_proj
- model.layers.5.self_attn.k_proj
- model.layers.1.self_attn.k_proj
- model.layers.0.self_attn.k_proj
- model.layers.3.self_attn.k_proj
- model.layers.19.self_attn.k_proj
- model.layers.20.self_attn.k_proj
- model.layers.21.self_attn.k_proj
- model.layers.22.self_attn.k_proj
- model.layers.23.self_attn.k_proj
# self_attn.o_proj layers
- model.layers.18.self_attn.o_proj
- model.layers.11.self_attn.o_proj
- model.layers.13.self_attn.o_proj
- model.layers.14.self_attn.o_proj
- model.layers.16.self_attn.o_proj
- model.layers.17.self_attn.o_proj
- model.layers.0.self_attn.o_proj
- model.layers.5.self_attn.o_proj
- model.layers.15.self_attn.o_proj
- model.layers.12.self_attn.o_proj
- model.layers.10.self_attn.o_proj
- model.layers.6.self_attn.o_proj
- model.layers.7.self_attn.o_proj
- model.layers.9.self_attn.o_proj
- model.layers.8.self_attn.o_proj
- model.layers.2.self_attn.o_proj
- model.layers.4.self_attn.o_proj
- model.layers.1.self_attn.o_proj
- model.layers.3.self_attn.o_proj
- model.layers.19.self_attn.o_proj
- model.layers.20.self_attn.o_proj
- model.layers.21.self_attn.o_proj
- model.layers.22.self_attn.o_proj
- model.layers.23.self_attn.o_proj
# self_attn.q_proj layers
- model.layers.2.self_attn.q_proj
- model.layers.4.self_attn.q_proj
- model.layers.5.self_attn.q_proj
- model.layers.7.self_attn.q_proj
- model.layers.6.self_attn.q_proj
- model.layers.9.self_attn.q_proj
- model.layers.10.self_attn.q_proj
- model.layers.1.self_attn.q_proj
- model.layers.18.self_attn.q_proj
- model.layers.8.self_attn.q_proj
- model.layers.15.self_attn.q_proj
- model.layers.14.self_attn.q_proj
- model.layers.17.self_attn.q_proj
- model.layers.16.self_attn.q_proj
- model.layers.12.self_attn.q_proj
- model.layers.13.self_attn.q_proj
- model.layers.11.self_attn.q_proj
- model.layers.0.self_attn.q_proj
- model.layers.3.self_attn.q_proj
- model.layers.19.self_attn.q_proj
- model.layers.20.self_attn.q_proj
- model.layers.21.self_attn.q_proj
- model.layers.22.self_attn.q_proj
- model.layers.23.self_attn.q_proj
# self_attn.v_proj layers
- model.layers.18.self_attn.v_proj
- model.layers.17.self_attn.v_proj
- model.layers.16.self_attn.v_proj
- model.layers.11.self_attn.v_proj
- model.layers.13.self_attn.v_proj
- model.layers.10.self_attn.v_proj
- model.layers.12.self_attn.v_proj
- model.layers.14.self_attn.v_proj
- model.layers.8.self_attn.v_proj
- model.layers.6.self_attn.v_proj
- model.layers.15.self_attn.v_proj
- model.layers.9.self_attn.v_proj
- model.layers.7.self_attn.v_proj
- model.layers.4.self_attn.v_proj
- model.layers.3.self_attn.v_proj
- model.layers.5.self_attn.v_proj
- model.layers.2.self_attn.v_proj
- model.layers.1.self_attn.v_proj
- model.layers.0.self_attn.v_proj
- model.layers.19.self_attn.v_proj
- model.layers.20.self_attn.v_proj
- model.layers.21.self_attn.v_proj
- model.layers.22.self_attn.v_proj
- model.layers.23.self_attn.v_proj
